[project]
name = "crew-ai-integration"
version = "0.1.0"
description = "CrewAI integration for Open Canvas"
requires-python = ">=3.9"
dependencies = [
    "crewai>=0.11.0",
    "langchain>=0.1.0",
    "pydantic>=2.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
    "python-dotenv>=1.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/crew_ai_integration"] 